#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O -J $PROXY $1; cd -
}

REPO=bagisto/bagisto
VERSION=$(gh_releases ${REPO} | grep -v "ALPHA\|BETA" | sort -V | tail -1)
URL="https://github.com/${REPO}/archive/${VERSION}.tar.gz"
SRC=/usr/local/src

dl $URL $SRC
