#!/bin/bash -ex

DB_NAME=bagisto
DB_USER=bagisto
DB_PASS=$(mcookie)

ADMIN_USER="admin"
ADMIN_DOMAIN="example.com"
ADMIN_MAIL="${ADMIN_USER}@${ADMIN_DOMAIN}"
ADMIN_PASS=turnkey1

SRC=/usr/local/src
WEBROOT=/var/www/bagisto
CONF=$WEBROOT/.env

LOC_SHARE=/usr/local/share
LOC_BIN=/usr/local/bin

# install Bagisto
tar xf $SRC/bagisto-*.tar.gz -C /var/www
mv $WEBROOT* $WEBROOT
rm -f $SRC/bagisto-*.tar.gz

service mysql start

mysqladmin create $DB_NAME
mysql --batch --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# Ensure that turnkey-artisan knows where webroot is
sed -i "\|^export WEBROOT| s|=.*|="$WEBROOT"|" /usr/local/bin/turnkey-artisan

cd $WEBROOT
chown -R www-data:www-data $WEBROOT
turnkey-composer install --no-dev --prefer-source || true
tkl-composer-squash-vendor

[[ ! -f "$CONF" ]] && cp $CONF.example $CONF

sed -i "\|APP_URL=|s|=.*|=http://localhost|" $CONF
sed -i "\|DB_DATABASE=|s|=.*|=$DB_NAME|" $CONF
sed -i "\|DB_USERNAME=|s|=.*|=$DB_USER|" $CONF
sed -i "\|DB_PASSWORD=|s|=.*|=$DB_PASS|" $CONF
sed -i "\|APP_DEBUG=|s|=.*|=false|" $CONF
sed -i "\|MAIL_DRIVER=|s|=.*|=mail|" $CONF
sed -i "\|MAIL_HOST=|s|=.*|=localhost|" $CONF
sed -i "\|MAIL_FROM_ADDR=|s|=.*|=$ADMIN_MAIL|" $CONF
sed -i "\|MAIL_REPLYTO_ADDR=|s|=.*|=$ADMIN_MAIL|" $CONF

chown www-data:www-data $CONF
echo 0 | turnkey-artisan bagisto:install

mysql --batch --execute "update bagisto.admins set name='$ADMIN_USER' where id='1';"
/usr/lib/inithooks/bin/bagisto.py --email="$ADMIN_MAIL" --pass="$ADMIN_PASS"

turnkey-artisan config:cache
turnkey-artisan key:generate --force
turnkey-artisan config:clear

a2dissite 000-default
a2enmod headers
a2ensite bagisto

a2enmod rewrite

service mysql stop
