#!/bin/bash -e
# regenerate bagisto secrets and mysql user password

. /etc/default/inithooks

WEBROOT=/var/www/bagisto
CONF=$WEBROOT/.env

DB_USER=bagisto
DB_PASS=$(mcookie)

sed -i "\|DB_PASSWORD=|s|=.*|=$DB_PASS|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user="$DB_USER" --pass="$DB_PASS"

turnkey-artisan config:cache
turnkey-artisan key:generate --force
turnkey-artisan config:clear

ADMIN_API_KEY=$(echo $(base64 <<< $(mcookie)$(mcookie)) | sed "s|[[:space:]]||;s|=||;s|/||" | cut -c -80)
mysql --execute "update bagisto.admins set api_token='$ADMIN_API_KEY' where id=1;"
