#!/bin/bash -e
# set invoice bagisto admin password & email

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF

$INITHOOKS_PATH/bin/bagisto.py --pass="$APP_PASS" --email="$APP_EMAIL"
